### ISSUE TITLE
"Ghost pixels" at the end of payload

### ISSUE THREAD

**Issue by hputzek** [hputzek/little-stream-protocol#6]
The payload has 1-x "ghost pixels" at the end.
Example: 
A stripe length of 200 px results in an actual payload of more than 200px

**Comment by martinberlin** [comment]
Note for me it's always 2 ghost pixels at the end. Even though I see only one appearing intermittently on the HEX preview.
Color is working right now. I just had the wrong RGBW setting when I'm using RGB. I have also part of your strip so I can test with 4 bytes per pixel too.

**Comment by hputzek** [comment]
> it would be nice to have a trigger button that just turns on the last pixel of the length you selected
@martinberlin for a start you can use the "random" animation because it always lights up all pixels - so it's easy to see the selected length this way.

Did you already find out if the ghost pixel thing is caused by firmware or JS part?
If it's firmware feel free to close this issue.

**Comment by martinberlin** [comment]
No it's not firmware. Like I commented some days ago, the Frontend is generating this. And you can even see it in the preview. 
After it's fixed I will check again to see if there is any Firmware thing that is failing but I didn't saw it. My presumption is that the tester is sending this extra 2 pixels.

**Comment by hputzek** [comment]
Hi @martinberlin 
please have a look at `feature/split-up-frames`#16
There was indeed a problem in snake mode which I fixed.
I could not see any other issue, if there is still something wrong please let me know.

**Comment by martinberlin** [comment]
This is still not working like it should in snake more. It's lighting with random colors at the beginning of the Strip ( 10 pixels ) will show you later when we speak
